In [16]:
import pandas as pd
data = pd.read_csv('/content/final_perfume_data.csv', encoding='latin-1')

In [17]:
data

Name  ...                                          Image URL
0                    Tihota Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
1                             Sola Parfum  ...  https://static.luckyscent.com/images/products/...
2                          Kagiroi Parfum  ...  https://static.luckyscent.com/images/products/...
3            Velvet Fantasy Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
4     A Blvd. Called Sunset Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
...                                   ...  ...                                                ...
2186           Perfect Veil Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
2187                  Scent Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
2188                 Bronze Eau de Parfum  ...  https://static.luckyscent.com/images/products/...
2189         Monyette Paris Fragrance Oil  ...  https://static.luckyscent.com/images/products/...
2190                   1270 Eau de Parfum  ...  https://static.luckyscent.com/images/products/...

[2191 rows x 5 columns]

In [18]:
text = data[['Description']]
text.columns = ['description']
text

description
0      Rapa Nui for sugar, Tihota is, quite simply, ...
1      A tribute to the expanse of space extending f...
2      An aromatic ode to the ancient beauty of Japa...
3      Velvet Fantasy is a solar fragrance where cit...
4      There's no way A Lab On Fire could relocate t...
...                                                 ...
2186   This was created to smell like clean, naked s...
2187   Scent is Costume Nationals debut fragrance. W...
2188   Bronze is a naughty little vixen of a scent, ...
2189   This isn't just sexy, it's “big night out” se...
2190   Named for the year the Frapin family establis...

[2191 rows x 1 columns]

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import re
from PIL import Image
from io import BytesIO
from nltk.tokenize import RegexpTokenizer, word_tokenize
import nltk
from nltk.corpus import stopwords

In [20]:
# nltk.download('stopwords')
# nltk.download('punkt')
stop_word = stopwords.words('english')


In [52]:
text['clean_docs'] = text['description'].str.replace(r'[^a-zA-Z]', ' ')
text['clean_docs'] = text['clean_docs'].str.lower()
text

description                                         clean_docs
0      Rapa Nui for sugar, Tihota is, quite simply, ...   rapa nui for sugar  tihota is  quite simply  ...
1      A tribute to the expanse of space extending f...   a tribute to the expanse of space extending f...
2      An aromatic ode to the ancient beauty of Japa...   an aromatic ode to the ancient beauty of japa...
3      Velvet Fantasy is a solar fragrance where cit...   velvet fantasy is a solar fragrance where cit...
4      There's no way A Lab On Fire could relocate t...   there s no way a lab on fire could relocate t...
...                                                 ...                                                ...
2186   This was created to smell like clean, naked s...   this was created to smell like clean  naked s...
2187   Scent is Costume Nationals debut fragrance. W...   scent is costume nationals debut fragrance  w...
2188   Bronze is a naughty little vixen of a scent, ...   bronze is a naughty little vixen of a scent  ...
2189   This isn't just sexy, it's “big night out” se...   this isn t just sexy  it s  big night out  se...
2190   Named for the year the Frapin family establis...   named for the year the frapin family establis...

[2191 rows x 2 columns]

In [53]:
text['clean_docs'] = text['clean_docs'].apply(lambda x: [w for w in word_tokenize(x) if w not in stop_word and len(w)>2])
text

description                                         clean_docs
0      Rapa Nui for sugar, Tihota is, quite simply, ...  [rapa, nui, sugar, tihota, quite, simply, one,...
1      A tribute to the expanse of space extending f...  [tribute, expanse, space, extending, sky, flow...
2      An aromatic ode to the ancient beauty of Japa...  [aromatic, ode, ancient, beauty, japan, kagiro...
3      Velvet Fantasy is a solar fragrance where cit...  [velvet, fantasy, solar, fragrance, citrus, ve...
4      There's no way A Lab On Fire could relocate t...  [way, lab, fire, could, relocate, los, angeles...
...                                                 ...                                                ...
2186   This was created to smell like clean, naked s...  [created, smell, like, clean, naked, skin, hon...
2187   Scent is Costume Nationals debut fragrance. W...  [scent, costume, nationals, debut, fragrance, ...
2188   Bronze is a naughty little vixen of a scent, ...  [bronze, naughty, little, vixen, scent, slinki...
2189   This isn't just sexy, it's “big night out” se...  [sexy, big, night, sexy, reel, sexy, amazing, ...
2190   Named for the year the Frapin family establis...  [named, year, frapin, family, established, cog...

[2191 rows x 2 columns]

In [54]:
print(text['description'][127])
print(text.loc[127])

 Passionate about native flora, Thays created unique parks. We have imagined the improbable encounters of multiple odors in his enchanting gardens. Originally born in France, Carlos Thays nevertheless was as true an Argentine as lived, with his landscape and park designs forming a significant and lasting element of Buenos Aires and beyond, parks that still have the capacity to enchant and amaze. To represent this in fragrance, Fueguia merges the delicate tones of mate flowers mingling with lush, creamy osmanthus and the vivid freshness of green tea. One sniff, and you're wandering the the Roman gardens of the Jardin Botanico, Thays' mansion ahead of you, lost in the natural splendor and in love with the world.
description     Passionate about native flora, Thays created ...
clean_docs     [passionate, native, flora, thays, created, un...
Name: 127, dtype: object


In [55]:
text['clean_docs'].replace('', np.nan, inplace=True)
text = text[text['clean_docs'].notna()]
text

description                                         clean_docs
0      Rapa Nui for sugar, Tihota is, quite simply, ...  [rapa, nui, sugar, tihota, quite, simply, one,...
1      A tribute to the expanse of space extending f...  [tribute, expanse, space, extending, sky, flow...
2      An aromatic ode to the ancient beauty of Japa...  [aromatic, ode, ancient, beauty, japan, kagiro...
3      Velvet Fantasy is a solar fragrance where cit...  [velvet, fantasy, solar, fragrance, citrus, ve...
4      There's no way A Lab On Fire could relocate t...  [way, lab, fire, could, relocate, los, angeles...
...                                                 ...                                                ...
2186   This was created to smell like clean, naked s...  [created, smell, like, clean, naked, skin, hon...
2187   Scent is Costume Nationals debut fragrance. W...  [scent, costume, nationals, debut, fragrance, ...
2188   Bronze is a naughty little vixen of a scent, ...  [bronze, naughty, little, vixen, scent, slinki...
2189   This isn't just sexy, it's “big night out” se...  [sexy, big, night, sexy, reel, sexy, amazing, ...
2190   Named for the year the Frapin family establis...  [named, year, frapin, family, established, cog...

[2191 rows x 2 columns]

In [45]:
import urllib.request
urllib.request.urlretrieve("https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz", \
                           filename="GoogleNews-vectors-negative300.bin.gz")

('GoogleNews-vectors-negative300.bin.gz',
 <http.client.HTTPMessage at 0x7f0869460c90>)

In [60]:
corpus = [word for word in text['clean_docs']]
corpus[:3]
print(len(corpus))

2191


In [58]:
from gensim.models import Word2Vec
w2v_model = Word2Vec(size=300, window=5, min_count=2, workers=-1)

In [59]:
w2v_model.build_vocab(corpus)

In [63]:
w2v_model.intersect_word2vec_format('GoogleNews-vectors-negative300.bin.gz', lockf=1.0, binary=True)

In [64]:
w2v_model.train(corpus, total_examples=w2v_model.corpus_count, epochs=15)

(0, 0)

In [69]:
w2v_model.wv.most_similar('tihota')

[('illicit', 0.19407272338867188),
 ('stony', 0.19377097487449646),
 ('unconventional', 0.18916842341423035),
 ('tempering', 0.18904151022434235),
 ('occasion', 0.1883271336555481),
 ('undercurrent', 0.1860732138156891),
 ('gathering', 0.18290375173091888),
 ('exuberant', 0.18240675330162048),
 ('adventurous', 0.181054025888443),
 ('reward', 0.1798231601715088)]

In [68]:
def count_word(word):
    return sum([docs.count(word) for docs in text['clean_docs']])

count_word('tihota')

4

In [93]:
w2v_model.wv.save_word2vec_format('perfume_w2v')

In [70]:
w2v_model.wv.most_similar('citrus')

[('grape', 0.633855402469635),
 ('strawberry', 0.6328265070915222),
 ('grapefruit', 0.6270824670791626),
 ('tomato', 0.6158294677734375),
 ('mango', 0.6063134670257568),
 ('fruit', 0.5927562713623047),
 ('blueberry', 0.5914932489395142),
 ('oranges', 0.59128737449646),
 ('almond', 0.5883358716964722),
 ('peaches', 0.5836828351020813)]

In [84]:
x = np.array([[1,2,3],[4,5,6]])
np.mean(x, axis=0)

array([2.5, 3.5, 4.5])

In [71]:
def vectors(doc_list):
    doc_embedding_list = []
    for doc in doc_list:
        doc2vec = [w2v_model[word] for word in doc 
                   if word in w2v_model.wv.vocab] or None
        
        if doc2vec:
            doc_embedding_list.append(np.mean(doc2vec, axis=0))
        
    return doc_embedding_list

doc_embedding_list = vectors(text['clean_docs'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """


In [72]:
len(doc_embedding_list)

2191

In [73]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sin = cosine_similarity(doc_embedding_list, doc_embedding_list)
cos_sin.shape

(2191, 2191)

In [76]:
user_input = "It would be nice to have a refreshing scent like orange and a cool scent like the sea."
user_input2 = "Passionate about native flora, Thays created unique parks. We have imagined the improbable encounters of multiple odors in his enchanting gardens."

In [77]:
def user_input_preprocessed(user_input):
    res = re.sub('[^a-zA-Z]', ' ', user_input)
    res = [w for w in word_tokenize(res.lower()) 
                if w not in stop_word and len(w)>2]
    
    return res

In [78]:
user_vec = user_input_preprocessed(user_input)
user_vec2 = user_input_preprocessed(user_input2)

In [79]:
print(f'{user_vec}\n{user_vec2}')

['would', 'nice', 'refreshing', 'scent', 'like', 'orange', 'cool', 'scent', 'like', 'sea']
['passionate', 'native', 'flora', 'thays', 'created', 'unique', 'parks', 'imagined', 'improbable', 'encounters', 'multiple', 'odors', 'enchanting', 'gardens']


In [80]:
def avg_vectors(word_list):
    v = [w2v_model[w] for w in word_list if w in w2v_model.wv.vocab]
    return np.mean(v, axis=0) if v else None

In [81]:
user_vec = avg_vectors(user_vec)
user_vec2 = avg_vectors(user_vec2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [83]:
cosine_similarity([user_vec2], doc_embedding_list).shape

(1, 2191)

In [86]:
x = np.array([[3,5,2,1]])
np.argsort(x[0])[::-1]

array([1, 0, 2, 3])

In [ ]:
x = np.array([[3,1,2],[4,6,5]])
np.sort(x, axis=1)

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
def recommendation(user_input, top=5):
    user_vec = avg_vectors(user_input_preprocessed(user_input))
    sim = cosine_similarity([user_vec], doc_embedding_list)
    sorted_args = np.argsort(sim[0])[::-1]
    # sorted_args = (np.argsort(sim, axis=1)[0])[::-1]
    sorted_args = sorted_args[:top]
    return list(zip(sorted_args, sim[0, sorted_args]))

In [88]:
recommended = recommendation(user_input2)
recommended

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


[(127, 0.84693074),
 (397, 0.72445345),
 (438, 0.72020984),
 (1619, 0.7202037),
 (1129, 0.7194506)]

In [90]:
indecies = [r[0] for r in recommended]
print(user_input2)
data[['Description', 'Notes']].loc[indecies]

Passionate about native flora, Thays created unique parks. We have imagined the improbable encounters of multiple odors in his enchanting gardens.


Description                                              Notes
127    Passionate about native flora, Thays created ...                 Mate flowers, Osmanthus, Green tea
397    A fragrance that traverses boundaries and con...   Oud Laos, Oud Bengal, Oud Trat, Rum, Vanilla,...
438    From the Thai for "forest, " Aran is an encha...   Goat hair, leather, frankincense, civet, cast...
1619   Les Jardins d'Armide are a symbol of beauty, ...   Rose, orange blossom, iris powder, florentine...
1129   Jules VerneHe was born in Nantes, at the begi...   Grapefruit, Citrus, Tangerine, Eucalyptus, Nu...

In [92]:
recommended2 = recommendation(user_input)
indecies = [r[0] for r in recommended2]
print(user_input)
data[['Description', 'Notes']].loc[indecies]

It would be nice to have a refreshing scent like orange and a cool scent like the sea.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


Description                                              Notes
1547   If you wanted a gentle, easy, casual fragranc...                  Tobacco, castoreum, wood, leather
2028   "The fragrance aims to evoke superhero magnet...                                                NaN
1704   Coccobello is truly intriguing and not your t...   Palm Leaves, Gardenia, Coconut, Sea Salt, Van...
2032   Previously known as No. 5 in the series. We'd...   Fennel, Italian Bergamot, Lemon Murcia from S...
877    Every line needs a musk, and this is The Musc...       Ginger, beeswax, lavender, sandalwood, musks

In [96]:
from gensim.models import KeyedVectors
new_model = KeyedVectors.load_word2vec_format('/content/perfume_w2v')
new_model.wv.most_similar('citrus')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  This is separate from the ipykernel package so we can avoid doing imports until


[('grape', 0.633855402469635),
 ('strawberry', 0.6328265070915222),
 ('grapefruit', 0.6270824670791626),
 ('tomato', 0.6158294677734375),
 ('mango', 0.6063134670257568),
 ('fruit', 0.5927562713623047),
 ('blueberry', 0.5914932489395142),
 ('oranges', 0.59128737449646),
 ('almond', 0.5883358716964722),
 ('peaches', 0.5836828351020813)]